version: '3.9'
 
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./web_src/public:/var/www/html/
      - ./web_src/:/var/www/
    ports:
      - 8080:80

  db:
    container_name: mysql8
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: practice
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - db
    ports:
      - "89:80"
    environment:
      - "PMA_HOST=db"
      - "PMA_USER=test"
      - "PMA_PASSWORD=test"